# Generated by Django 6.0 on 2025-12-19 16:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LightingCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_name', models.CharField(help_text='Symbol name as it appears in CAD', max_length=100, unique=True)),
                ('model_number', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('lumens', models.IntegerField(help_text='Light output in lumens', validators=[django.core.validators.MinValueValidator(0)])),
                ('wattage', models.FloatField(help_text='Power consumption in watts', validators=[django.core.validators.MinValueValidator(0)])),
                ('beam_angle', models.FloatField(help_text='Beam angle in degrees', validators=[django.core.validators.MinValueValidator(0)])),
                ('color_temp', models.IntegerField(help_text='Color temperature in Kelvin', validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='fixtures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lighting Catalog Entry',
                'verbose_name_plural': 'Lighting Catalog',
                'ordering': ['symbol_name'],
            },
        ),
        migrations.CreateModel(
            name='CADFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='Untitled Project', max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='cad_files/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cad_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CAD File',
                'verbose_name_plural': 'CAD Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('pdf', 'PDF Report'), ('csv', 'CSV Report')], max_length=10)),
                ('file_path', models.FileField(upload_to='reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('cad_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='lighting.cadfile')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.FloatField(help_text='Area in square meters', validators=[django.core.validators.MinValueValidator(0)])),
                ('height', models.FloatField(default=3.0, help_text='Height in meters', validators=[django.core.validators.MinValueValidator(0)])),
                ('required_lux', models.FloatField(default=300, help_text='Required illuminance in lux', validators=[django.core.validators.MinValueValidator(0)])),
                ('cad_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='lighting.cadfile')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('x_coordinate', models.FloatField(blank=True, help_text='X position from CAD', null=True)),
                ('y_coordinate', models.FloatField(blank=True, help_text='Y position from CAD', null=True)),
                ('lighting_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='lighting.lightingcatalog')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='lighting.room')),
            ],
            options={
                'verbose_name': 'Fixture',
                'verbose_name_plural': 'Fixtures',
                'ordering': ['room', 'lighting_catalog'],
            },
        ),
    ]
